DECLARE @GameId UNIQUEIDENTIFIER;
DECLARE @ServiceName NVARCHAR(30);
DECLARE @Result INT;

BEGIN TRY
	BEGIN TRANSACTION

		EXEC DBO.GSP_AddGameToService @GameId, @ServiceName, @Result = @Result OUTPUT;

		IF @Result < 1
			RAISERROR('Thêm service không thành công!', 16, 1);

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION;

	SET @Result = 0;
END CATCH

SELECT @Result;