DECLARE @Title NVARCHAR(100);
DECLARE @Genre NVARCHAR(100);
DECLARE @Description NVARCHAR(MAX);
DECLARE @Details NVARCHAR(MAX);
DECLARE @GameId UNIQUEIDENTIFIER;

BEGIN TRY
	BEGIN TRANSACTION

		EXEC DBO.GP_CreateGame @Title, @Genre, @Description, @Details, @GameId = @GameId OUTPUT;

		IF @GameId IS NULL
			RAISERROR('Tạo game không thành công!', 16, 1);

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION;

	SET @GameId = NULL;
END CATCH

SELECT @GameId;