DECLARE @Page INT = 1;
DECLARE @Limit INT = 10;

BEGIN TRY
	BEGIN TRANSACTION
		EXEC GP_GetGamePaginate @Page = @Page, @Limit = @Limit;
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0	
		ROLLBACK TRANSACTION;

	SELECT NULL AS GamesPage;
END CATCH

