--DECLARE @GameId UNIQUEIDENTIFIER;

BEGIN TRY
	BEGIN TRANSACTION
		EXEC DBO.GP_GetGameAllInfo @GameId;
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION;

	SELECT NULL AS GameAllInfo;
END CATCH