-- DECLARE @UserId UNIQUEIDENTIFIER = 'B570F1D1-B092-4A16-BD0F-F73837A5F3DF';
-- DECLARE @OldPassword varchar(100) = 'Admin1@123'
-- DECLARE @NewPassword varchar(100) = 'Admin1@321'

BEGIN TRY
    BEGIN TRANSACTION;

        EXEC DBO.UP_ChangePassword @UserId, @OldPassword, @NewPassword;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    SELECT -1 ERROR_CODE;
END CATCH

