DECLARE @UserId UNIQUEIDENTIFIER = 'b570f1d1-b092-4a16-bd0f-f73837a5f3dfF';
DECLARE @Username VARCHAR(100) = 'admin1'

BEGIN TRY
    BEGIN TRANSACTION;

        EXEC DBO.UP_UpdateUsername @UserId, @Username;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    SELECT -1 ERROR_CODE;
END CATCH

