DECLARE @UserId UNIQUEIDENTIFIER = 'B570F1D1-B092-4A16-BD0F-F73837A5F3DF';
DECLARE @Password varchar(100) = 'admin1@123'

BEGIN TRY
    BEGIN TRANSACTION;

        EXEC DBO.UP_DeleteUser @UserId, @Password;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    SELECT -1 ERROR_CODE
END CATCH

