--DECLARE @UserId UNIQUEIDENTIFIER = '838844B4-24CC-44B6-A990-3D01B6B5F3DD';

BEGIN TRY
    BEGIN TRANSACTION
    
        EXEC DBO.UP_GetUserDetails @UserId;

    COMMIT TRANSACTION
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 
        ROLLBACK TRANSACTION;

    SELECT NULL AS UserDetails;
END CATCH