-- DECLARE @Username VARCHAR(100) = 'admin';
BEGIN TRY
    BEGIN TRANSACTION

        SELECT userId
        FROM Users
        WHERE username = @Username

    COMMIT TRANSACTION
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 
        ROLLBACK TRANSACTION;

    SELECT  NULL AS UserInfo
END CATCH