-- DECLARE @UserId VARCHAR(100) = '2d1f1b33-8d1e-4722-b566-125fca142750';
BEGIN TRY
    BEGIN TRANSACTION

        EXEC DBO.UP_GetUserDisplayInfo @UserId;

    COMMIT TRANSACTION
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 
        ROLLBACK TRANSACTION;

    SELECT  NULL AS UserInfo
END CATCH