-- DECLARE @UserId UNIQUEIDENTIFIER = '298831ee-5db0-43c5-9b5b-007a56e21a64';
-- DECLARE @Page INT = 1;
-- DECLARE @Limit INT = 10;
BEGIN TRY
    BEGIN TRANSACTION
    
        EXEC DBO.UUP_GetUserFollowingPagination @UserId, @Page, @Limit;

    COMMIT TRANSACTION
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 
        ROLLBACK TRANSACTION;

    SELECT NULL AS UserAll;
END CATCH