
CREATE DATABASE QLHETHONG;

GO
USE QLHETHONG;

CREATE TABLE USER_ACCOUNT
(
	_USERNAME VARCHAR(20),
	_PASSWORD_HASH VARBINARY(32),
    _ID UNIQUEIDENTIFIER,
	PRIMARY KEY (_USERNAME)
);

CREATE TABLE USER_INFO
(
    _ID UNIQUEIDENTIFIER DEFAULT NEWID(),
	_NAME NVARCHAR(50),
	_BIRTHDAY DATE,
	_PHONENUMBER CHAR(10),
	_EMAIL VARCHAR(50),
	_ADDRESS NVARCHAR(100),
	PRIMARY KEY (_ID)
);

GO
ALTER TABLE USER_ACCOUNT
	ADD CONSTRAINT FK_USERACOUNT_USERINFO
	FOREIGN KEY (_ID)
	REFERENCES USER_INFO(_ID);
