-- Tạo thông tin nền
INSERT INTO USER_INFO (_NAME, _BIRTHDAY, _PHONENUMBER, _EMAIL, _ADDRESS)
VALUES (N'UNKNOWN', GETDATE(), NULL, NULL, NULL);

-- Lấy _ID vừa tạo ra
DECLARE @ID UNIQUEIDENTIFIER
SELECT @ID = _ID FROM USER_INFO WHERE _NAME = 'UNKNOWN';

-- Tạo tài khoản với ID đó
INSERT INTO USER_ACCOUNT (_USERNAME, _PASSWORD_HASH, _ID)
VALUES (@USERNAME, HASHBYTES('SHA2_256', CONVERT(VARCHAR(100), @PASSWORD)), @ID);