-- DECLARE @UserId UNIQUEIDENTIFIER = 'a96e7ea1-425b-4c86-a9d3-8ed076db7e9a';
-- DECLARE @Username VARCHAR(100) = 'admin1'

BEGIN TRY
    BEGIN TRANSACTION;

        EXEC DBO.UP_UpdateUsername @UserId, @Username;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    SELECT -1 ERROR_CODE;
END CATCH

