DECLARE @Email varchar(100) = 'admin1@gmail.com'

BEGIN TRY
    BEGIN TRANSACTION;

        EXEC DBO.UP_ForgetPassword @Email;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    SELECT -1 ERROR_CODE;
END CATCH

