name: Build Server Winform Kontroller App

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Server/**'  # 👈 Chỉ build khi có thay đổi trong thư mục này

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Lấy mã nguồn
      uses: actions/checkout@v3

    - name: Cài .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Build WinForm dạng self-contained vào thư mục BuildOutput
      run: dotnet publish ./src/Server/Server.csproj -c Release -o ./BuildOutput --self-contained true -r win-x64 /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true

    - name: Thêm tài nguyên ngoài vào thư mục BuildOutput
      run: |
        if (Test-Path "./extra_files") {
          Copy-Item -Path ./extra_files/* -Destination ./BuildOutput/ -Recurse -Force
        }

    - name: Tạo file ZIP từ thư mục BuildOutput
      run: Compress-Archive -Path ./BuildOutput/* -DestinationPath ./KontrollerApp.zip

    - name: Upload artifact KontrollerApp.zip
      uses: actions/upload-artifact@v4
      with:
        name: KontrollerApp
        path: KontrollerApp.zip
