name: Build Server Winform Kontroller App

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Server/**'  # Chỉ build khi thay đổi trong thư mục này

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Lấy mã nguồn
      uses: actions/checkout@v3

    - name: Cài .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Cài Python & gdown
      run: |
        python -m pip install --upgrade pip
        pip install gdown

    - name: Tải extra_files.zip từ Google Drive bằng gdown
      run: |
        gdown https://drive.google.com/uc?id=1HuwwtuoEaj-EV7qxzNsAsIlJRHqKQv71

    - name: Kiểm tra file extra_files.zip
      run: dir extra_files.zip

    - name: Giải nén extra_files.zip
      run: |
        powershell Expand-Archive -Path extra_files.zip -DestinationPath extra_files

    - name: Build WinForm dạng self-contained vào thư mục BuildOutput
      # run: dotnet publish ./src/Server/Server.csproj -c Release -o ./BuildOutput --self-contained true -r win-x64 /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true
      run: dotnet publish ./src/Server/Server.csproj -c Release -o ./BuildOutput --self-contained true -r win-x64
    
    - name: Thêm tài nguyên ngoài vào thư mục BuildOutput
      shell: powershell
      run: |
        if (Test-Path "./extra_files") {
          Get-ChildItem ./extra_files | ForEach-Object {
            Copy-Item $_.FullName -Destination ./BuildOutput/ -Recurse -Force
          }
        }

    # - name: Tạo file ZIP từ thư mục BuildOutput
    #   run: Compress-Archive -Path ./BuildOutput/* -DestinationPath ./KontrollerApp.zip

    # - name: Upload artifact KontrollerApp.zip
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: KontrollerApp
    #     path: KontrollerApp.zip

    - name: Upload thư mục BuildOutput (GitHub tự zip khi tải về)
      uses: actions/upload-artifact@v4
      with:
        name: KontrollerApp
        path: BuildOutput
        if-no-files-found: error
        retention-days: 7
