name: Build Server Winform Kontroller App 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Lấy mã nguồn
      uses: actions/checkout@v3

    - name: Cài .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Build dạng self-contained vào thư mục BuildOutput
      run: dotnet publish ./src/Server/Server.csproj -c Release -o ./BuildOutput --self-contained true -r win-x64 /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true

    - name: Tạo file ZIP (tuỳ chọn)
      run: Compress-Archive -Path ./BuildOutput/* -DestinationPath ./KontrollerApp.zip

    - name: Upload artifact (tuỳ chọn)
      uses: actions/upload-artifact@v4
      with:
        name: KontrollerApp
        path: KontrollerApp.zip
