name: Auto Build Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -f src/ServerConsole/Dockerfile -t lucifer251/serverconsole:latest src/ServerConsole


      - name: Push Docker image
        run: docker push lucifer251/serverconsole:latest
